

using System.Collections.Generic;
using System.Linq;
using EryfitProxy.Kernel.Core;

namespace EryfitProxy.Kernel.Rules.Filters
{
    /// <summary>
    ///     Select exchanges that contain tag
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchanges having tag."
    )]
    public class HasTagFilter : Filter
    {
        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName { get; } = "Has any tag";

        public override bool PreMadeFilter { get; } = true;

        protected override bool InternalApply(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            return exchange?.Tags?.Any() ?? false;
        }

        public override IEnumerable<FilterExample> GetExamples()
        {
            var defaultSample = GetDefaultSample();

            if (defaultSample != null)
                yield return defaultSample;
        }
    }
}
